site_name: NADA
repo_url: https://github.com/navikt/nada
edit_uri: ./edit/main/docs
site_url: https://docs.knada.io
theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.instant
    - navigation.tabs
  logo: 'img/logo.svg'
  favicon: img/favicon.ico
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
extra:
  search:
    language: 'no'
plugins:
  - search
  - build_plantuml:
      output_format: "svg"
      input_extensions: "puml"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      css_class: codehilite
      linenums_style: pymdownx-inline
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - NADA:
    - Hva og hvorfor?:
      - Hva er nada?: konsepter/data-mesh.md
      - Hvorfor har vi nada?: index.md
      - Data som produkt?: dele-data/dataprodukt.md
      - Spilleregler: ""
      - Hvordan funker det hos oss?: prosessere-data/getting-started.md
      - FAQ: ""
    - Produsere data:
      - Bygge produkt:
        - Innhente: ""
        - Transformere: ""
        - Kvalitetssikre: ""
        - Laste data: ""
        - Skedulere:
           - Cloud composer: prosessere-data/skedulering/cloud-composer.md
           - Naisjobs: prosessere-data/skedulering/naisjobs.md
           - Notebook GCP CronJob: prosessere-data/skedulering/notebook-gcp-cronjob.md
           - Scheduled query: prosessere-data/skedulering/scheduled-query.md
        - Registrere: dele-data/registrere-dataprodukt.md
        - Deploye: ""
      - Forvalte:
        - Tilgangsstyre: dataplassen/tilgangsstyring.md
        - Overvåke: ""
        - Avvikle: ""
      - Tutorials:
        - ETL på NAIS: guider/etl-paa-nais.md
        - Laste opp fil: dele-data/laste-opp-fil.md
    - Konsumere data:
      - Finne og forstå: finne-data/navdata.md
      - Få tilgang:
        - Personlig bruker: ""
        - Serviceaccounts: dataplassen/lag-serviceaccount.md
      - Finne innsikt:
        - Notebooks på GCP: prosessere-data/notebooks.md
      - Dele innsikt:
        - Datafortelling: dele-innsikt/datafortelling.md
        - Metabase: dele-innsikt/metabase.md
    - Legacy:
      - KNADA on-prem:
          - Kom i gang: prosessere-data/onprem/getting-started.md
          - Airflow: prosessere-data/onprem/airflow.md
          - Jupyterhub: prosessere-data/onprem/jupyterhub.md
          - Vault: prosessere-data/onprem/vault.md
          - Dataverk:
              - Hva er dataverk: prosessere-data/onprem/dataverk/hva-er-dataverk.md
              - Metadata: prosessere-data/onprem/dataverk/metadata.md
              - Publisering fra GCP: prosessere-data/onprem/dataverk/publisering-fra-gcp.md
              - Slette datapakker: prosessere-data/onprem/dataverk/slette-datapakker.md
              - Settings:
                  - Settingsfil: prosessere-data/onprem/dataverk/settings/settings.md
                  - Postgres konfigurasjon: prosessere-data/onprem/dataverk/settings/postgres.md
      - Datapakker:
        - Datapakke: dele-innsikt/datapakker.md
        - Publisere: dele-innsikt/publisere-datapakker.md
    - Community:
      - Guider: ""

