site_name: NADA
repo_url: https://github.com/navikt/nada
edit_uri: ./edit/main/docs
site_url: https://docs.knada.io/
theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.instant
    - navigation.sections
    - content.tabs.link
  logo: 'img/logo.svg'
  custom_dir: custom_theme_overrides
  favicon: img/favicon.ico
extra:
  search:
    language: 'no'
  analytics:
    feedback:
        title: Fikk du svar på det du lurte på?
        ratings:
            - icon: material/thumb-down-outline
              name: Nei
              data: 0
              note: >-
                Takk! Kontakt oss gjerne på <a href="https://nav-it.slack.com/archives/CGRMQHT50">#nada på Slack</a> med tilbakemeldinger eller spørsmål.
            - icon: material/thumb-up-outline
              name: Ja
              data: 1
              note: >-
                Takk for tilbakemeldingen!
extra_javascript:
  - amplitude_javascript/events.js
plugins:
  - search
  - build_plantuml:
      output_format: "svg"
      input_extensions: "puml"
markdown_extensions:
  - abbr
  - toc:
      permalink: True
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Om NADA: index.md
  - Ordliste: ordliste.md
  - Juridisk:
    - Hva trenger jeg av dokumentasjon?: juridisk/dokumentasjon.md
    - Spilleregler: juridisk/spilleregler.md
    - Hvem lager spilleregler?: juridisk/hvem.md
    - Hvordan fyller jeg ut PVK?: juridisk/pvk.md
  - Dataprodukter:
    - Hva er et dataprodukt?: dataprodukter/dataprodukt.md
    - Kom i gang: dataprodukter/index.md
    - Få tilgang til datakilder: dataprodukter/dele/få-tilgang.md
    - Laste data fra kilde til BigQuery: dataprodukter/dele/dataoverføring.md
    - Legge til et dataprodukt: dataprodukter/dele/dataprodukt.md
    - Tilgangsstyring: dataprodukter/tilgangsstyring.md
  - Analysering:
    - Kom i gang: analyse/kom-i-gang.md
    - Jupyter notebooks:
      - Hva er Jupyter notebooks?: analyse/notebook/index.md
      - KNADA notebooks: analyse/notebook/knada-notebook.md
      - Google managed notebooks: analyse/notebook/managed-notebook.md
      - Generelle råd: analyse/notebook/generelt.md
    - Airflow: 
      - KNADA Airflow: analyse/airflow/knada-airflow.md
      - Google managed Airflow (Cloud Composer): analyse/airflow/managed-airflow.md
    - Metabase: analyse/metabase.md
    - Datafortellinger: analyse/datafortellinger.md
  - Vår visjon:
    - Data mesh: visjon/data_mesh.md
