site_name: NADA
repo_url: https://github.com/navikt/nada
edit_uri: ./edit/main/docs
site_url: https://docs.knada.io/
theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.instant
    - navigation.sections
    - content.tabs.link
  logo: 'img/logo.svg'
  custom_dir: custom_theme_overrides
  favicon: img/favicon.ico
extra:
  search:
    language: 'no'
  analytics:
    feedback:
        title: Fikk du svar på det du lurte på?
        ratings:
            - icon: material/thumb-down-outline
              name: Nei
              data: 0
              note: >-
                Takk! Kontakt oss gjerne på <a href="https://nav-it.slack.com/archives/CGRMQHT50">#nada på Slack</a> med tilbakemeldinger eller spørsmål.
            - icon: material/thumb-up-outline
              name: Ja
              data: 1
              note: >-
                Takk for tilbakemeldingen!
extra_javascript:
  - amplitude_javascript/events.js
plugins:
  - search
  - build_plantuml:
      output_format: "svg"
      input_extensions: "puml"
markdown_extensions:
  - abbr
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Om NADA: index.md
  - Juridisk:
    - Hva trenger jeg av dokumentasjon?: juridisk/dokumentasjon.md
    - Spilleregler: juridisk/spilleregler.md
    - Hvem lager spilleregler?: juridisk/hvem.md
  - Dataprodukter:
    - Hva er et dataprodukt?: dataprodukter/dataprodukt.md
    - Kom i gang: dataprodukter/index.md
    - Få tilgang til datakilder: dataprodukter/dele/få-tilgang.md
    - Føre over data: dataprodukter/dele/dataoverføring.md
    - Legg til et dataprodukt: dataprodukter/dele/dataprodukt.md
    - Tilgangsstyring: dataprodukter/tilgangsstyring.md
  - Analyse:
    - Kom i gang: analyse/komigang.md
    - Notebook:
      - Hva er en notebook?: analyse/notebook/index.md
      - Google managed notebooks: analyse/notebook/managed-notebook.md
      - Knada notebooks: analyse/notebook/knada-notebook.md
      - Generelle råd: analyse/notebook/generelt.md
    - Airflow: 
      - Google managed Airflow (Cloud Composer): analyse/airflow/managed-airflow.md
      - Knada Airflow: analyse/airflow/knada-airflow.md
    - Metabase: analyse/metabase.md
    - Datafortellinger: analyse/datafortellinger.md
  - Vår visjon:
    - Data mesh: visjon/data_mesh.md

  # - Hva er NADA?: index.md
  # - Prinsipper og spilleregler:
  #   - Prinsipper for data: intro/ny_retning.md
  #   - Om spilleregler: spilleregler/spilleregler_intro.md
  #   - Juridiske spilleregler: spilleregler/spilleregler_juridisk.md
  #   #- Øvrige spilleregler: spilleregler/spilleregler_annet.md
  # - Dataprodukter:
  #   - Hva er et dataprodukt?: dataprodukter/definisjon.md
  #   - Produsere:
  #     - Innhente: dataprodukter/produsere/innhente.md
  #     #- Transformere: dataprodukter/produsere/transformere.md
  #     #- Kvalitetssikre: dataprodukter/produsere/kvalitetssikre.md
  #     - Skedulere:
  #         - Cloud composer: dataprodukter/produsere/skedulering/cloud-composer.md
  #         - Naisjobs: dataprodukter/produsere/skedulering/naisjobs.md
  #         - Notebook GCP CronJob: dataprodukter/produsere/skedulering/notebook-gcp-cronjob.md
  #         - Scheduled query: dataprodukter/produsere/skedulering/scheduled-query.md
  #     - Registrere: dataprodukter/produsere/registrere.md
  #   - Forvalte:
  #     - Tilgangsstyre: dataprodukter/forvalte/tilgangsstyring.md
  #     - Overvåke: dataprodukter/forvalte/overvåke.md
  #   - Konsumere:
  #     - Finne og forstå: dataprodukter/konsumere/finne.md #finne-data/navdata.md
  #     - Få tilgang: dataprodukter/konsumere/tilgang.md
  #     - Lese: dataprodukter/konsumere/lese.md
  #   - Veiledninger:
  #       - ETL på NAIS: guider/etl-paa-nais.md
  #       - Laste opp fil: dataprodukter/produsere/laste_data.md
  # - Finne og dele innsikt:
  #   - Notebooks:
  #       - Overordnet: prosessere-data/notebook_intro.md
  #       - Komme i gang: prosessere-data/notebook_projects.md
  #       - Generelle veiledninger: prosessere-data/notebook_general.md
  #       - Spesifikt for kilder on-prem: prosessere-data/notebook_knada.md
  #       - KNADA GKE: prosessere-data/knada_gke.md
  #   - Datafortelling: dele-innsikt/datafortelling.md
  #   - Metabase: dele-innsikt/metabase.md
  # - Legacy:
  #   - KNADA on-prem:
  #       - Kom i gang: legacy/onprem/getting-started.md
  #       - Airflow: legacy/onprem/airflow.md
  #       - Jupyterhub: legacy/onprem/jupyterhub.md
  #       - Vault: legacy/onprem/vault.md
  #       - Dataverk:
  #           - Hva er dataverk: legacy/onprem/dataverk/hva-er-dataverk.md
  #           - Metadata: legacy/onprem/dataverk/metadata.md
  #           - Publisering fra GCP: legacy/onprem/dataverk/publisering-fra-gcp.md
  #           - Slette datapakker: legacy/onprem/dataverk/slette-datapakker.md
  #           - Settings:
  #               - Settingsfil: legacy/onprem/dataverk/settings/settings.md
  #               - Postgres konfigurasjon: legacy/onprem/dataverk/settings/postgres.md
  #   - Datapakker:
  #     - Datapakke: legacy/datapakker.md
  #     - Publisere: legacy/publisere-datapakker.md

