module.exports = {
  adr: [{ type: 'autogenerated', dirName: 'adr' }],
  concepts: [{ type: 'autogenerated', dirName: 'concepts' }],
  docs: [
    'README',
    {
      type: 'category',
      label: 'Finne data',
      items: [
        {
          type: 'autogenerated',
          dirName: 'finne-data',
        },
      ],
    },
    {
      type: 'category',
      label: 'Process data',
      items: [
        {
          type: 'autogenerated',
          dirName: 'process-data',
        },
      ],
    },
    {
      type: 'category',
      label: 'Share data',
      items: [
        {
          type: 'autogenerated',
          dirName: 'share-data',
        },
      ],
    },
    {
      type: 'category',
      label: 'Share insight',
      items: [
        {
          type: 'autogenerated',
          dirName: 'share-insight',
        },
      ],
    },
  ],
};
